# Generated by Django 5.0 on 2025-10-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='marks_obtained',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='grade',
            name='class_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='grade',
            name='exams_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='grade',
            name='subject_position',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='term',
            field=models.CharField(choices=[('first', 'First Term'), ('second', 'Second Term'), ('third', 'Third Term')], default='first', max_length=10),
        ),
        migrations.AddField(
            model_name='grade',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='grade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.CharField(blank=True, choices=[('1', 'Highest'), ('2', 'Higher'), ('3', 'High'), ('4', 'High Average'), ('5', 'Average'), ('6', 'Low Average'), ('7', 'Low'), ('8', 'Lower'), ('9', 'Lowest')], max_length=2),
        ),
        migrations.AlterField(
            model_name='grade',
            name='remarks',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
