# Generated by Django 5.0 on 2025-10-14 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_class_unique_together_remove_class_section'),
        ('students', '0003_remove_grade_exam_type_remove_grade_marks_obtained_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject', 'academic_year', 'term')},
        ),
    ]
