# Generated by Django 5.0 on 2026-01-11 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_galleryimage'),
        ('students', '0004_alter_grade_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('first', 'First Term'), ('second', 'Second Term'), ('third', 'Third Term')], default='first', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.classsubject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentExerciseScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remarks', models.CharField(blank=True, max_length=100)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.classexercise')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'unique_together': {('student', 'exercise')},
            },
        ),
    ]
