# Generated by Django 5.0 on 2025-10-18 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_importrun'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportRun',
        ),
    ]
