# Generated by Django 5.0 on 2026-01-10 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_galleryimage'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('First', 'First Term'), ('Second', 'Second Term'), ('Third', 'Third Term')], max_length=15)),
                ('week_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicyear')),
            ],
            options={
                'verbose_name': 'Duty Week',
                'verbose_name_plural': 'Duty Weeks',
                'ordering': ['start_date'],
                'unique_together': {('academic_year', 'term', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='DutyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Member', help_text='e.g. Senior Team Leader, Member', max_length=100)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teachers.dutyweek')),
            ],
            options={
                'ordering': ['role', 'teacher'],
                'unique_together': {('week', 'teacher')},
            },
        ),
    ]
