# Generated by Django 5.0 on 2026-01-11 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_resource'),
        ('teachers', '0002_dutyweek_dutyassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('topic', models.CharField(max_length=200)),
                ('objectives', models.TextField(help_text='Specific learning outcomes')),
                ('teaching_materials', models.TextField(blank=True, help_text='Materials needed for the lesson')),
                ('introduction', models.TextField(blank=True)),
                ('presentation', models.TextField(blank=True, help_text='Main teaching activity')),
                ('evaluation', models.TextField(blank=True, help_text='How students will be assessed')),
                ('homework', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.class', verbose_name='Class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-week_number', '-date_added'],
            },
        ),
    ]
