# Generated by Django 5.0 on 2025-10-21 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homework',
        ),
    ]
