# Generated manually to fix missing table issue
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_notification'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS "announcements_notification" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "message" varchar(255) NOT NULL,
                "is_read" boolean NOT NULL,
                "created_at" timestamp with time zone NOT NULL,
                "alert_type" varchar(20) NOT NULL,
                "recipient_id" bigint NOT NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED,
                "timetable_slot_id" bigint NULL REFERENCES "academics_timetable" ("id") DEFERRABLE INITIALLY DEFERRED
            );
            CREATE INDEX IF NOT EXISTS "announcements_notification_recipient_id_idx" ON "announcements_notification" ("recipient_id");
            CREATE INDEX IF NOT EXISTS "announcements_notification_timetable_slot_id_idx" ON "announcements_notification" ("timetable_slot_id");
            """,
            reverse_sql="DROP TABLE IF EXISTS \"announcements_notification\";"
        ),
    ]
