# Generated by Django 5.0 on 2025-10-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
