import os
import sys
import django
from django.db import connection

# Setup Django environment
sys.path.append(os.getcwd())
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'school_system.settings')
django.setup()

def fix_table():
    print("--- CHECKING FOR MISSING NOTIFICATION TABLE ---")
    with connection.cursor() as cursor:
        # Check if table exists
        cursor.execute("""
            SELECT exists(
                SELECT FROM information_schema.tables 
                WHERE table_name = 'announcements_notification'
            );
        """)
        exists = cursor.fetchone()[0]
        
        if not exists:
            print("⚠️ Table 'announcements_notification' MISSING. Creating manually...")
            # Raw SQL to reproduce the table structure
            # Note: Adjust fields to match your specific DB (Postgres assumed for Vercel/Neon)
            create_sql = """
            CREATE TABLE IF NOT EXISTS "announcements_notification" (
                "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "message" varchar(255) NOT NULL,
                "is_read" boolean NOT NULL,
                "created_at" timestamp with time zone NOT NULL,
                "alert_type" varchar(20) NOT NULL,
                "recipient_id" bigint NOT NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED,
                "timetable_slot_id" bigint NULL REFERENCES "academics_timetable" ("id") DEFERRABLE INITIALLY DEFERRED
            );
            CREATE INDEX "announcements_notification_recipient_id_idx" ON "announcements_notification" ("recipient_id");
            CREATE INDEX "announcements_notification_timetable_slot_id_idx" ON "announcements_notification" ("timetable_slot_id");
            """
            try:
                cursor.execute(create_sql)
                print("✅ Table 'announcements_notification' created successfully.")
            except Exception as e:
                print(f"❌ Failed to create table: {e}")
        else:
            print("✅ Table 'announcements_notification' already exists.")

if __name__ == '__main__':
    fix_table()
