# Generated by Django 5.0 on 2025-10-20 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(help_text="Identifier for the widget type (e.g., 'summary_stats', 'recent_grades')", max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='The display order of the widget on the dashboard.')),
                ('is_visible', models.BooleanField(default=True, help_text='Whether the widget is visible to the user.')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Custom configuration for the widget (e.g., specific class for grades).')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'order'],
                'unique_together': {('user', 'widget_type')},
            },
        ),
    ]
