# Generated by Django 5.0 on 2025-10-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name', 'academic_year')},
        ),
        migrations.RemoveField(
            model_name='class',
            name='section',
        ),
    ]
