# Generated by Django 5.0 on 2026-01-09 10:06

from django.db import migrations

def create_initial_school_info(apps, schema_editor):
    SchoolInfo = apps.get_model('academics', 'SchoolInfo')
    if not SchoolInfo.objects.exists():
        SchoolInfo.objects.create(
            name="DABOYA GIRLS MODEL JUNIOR HIGH SCHOOL",
            address="P.O. Box 6, Daboya, North Gonja District",
            phone="024-0852910",
            email="info@daboyagirlsmodel.edu.gh",
            motto="SUCCESS, OUR CONCERN"
        )

class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_schoolinfo'),
    ]

    operations = [
        migrations.RunPython(create_initial_school_info),
    ]
