# Generated by Django 5.0 on 2026-01-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_populate_school_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('caption', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('campus', 'Campus'), ('events', 'Events'), ('sports', 'Sports'), ('academics', 'Academics'), ('others', 'Others')], default='events', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
