# Generated by Django 5.0 on 2026-01-11 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='class_resources/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='academics.classsubject')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
